#--------------------------
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKETNAME : "ndn-it-flask-application-packages"
  EB_APPLICATION_NAME      : "MyFlask"
  EB_ENVIROPMENT_NAME      : "MyFlask-env"
  DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1" 

on: 
  push:
    branches: 
      - master
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-accessk-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region            : ${{ env.AWS_REGION_NAME }} 
      - name: Copy Deployment to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKETNAME }}/
      - name: Print Happy Message for CI finish  
        run: echo "CI Pipeline part Finished succesfully"


         
         
         
        
        

        
